### ISSUE TITLE
Touchable

### ISSUE THREAD

**Issue by rogchap** [silentcloud/react-native-page-control#4]
Might be wrong, as it's been awhile since I've done pure UIKit stuff, but I'm sure the iOS PageControl allows you to tap/touch the indicator to move/jump to that page.
Any plans to add this?

**Comment by silentcloud** [comment]
@rogchap  I can only add a hook function

**Comment by giogus** [comment]
@silentcloud Please add this function! :)

**Comment by silentcloud** [comment]
@giogus version 1.0.6
